language: python
python:
    - "2.7"
before_install:
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install gfortran
install:
    - sudo apt-get update
    - sudo apt-get install python-dev
    - sudo apt-get install python-setuptools
    - sudo apt-get install python-numpy
    - sudo apt-get install zlib1g-dev
    - sudo apt-get install python-scipy python-matplotlib python-nose
    - sudo easy_install pip
    - sudo pip install cython
    - pip install numpy
    - pip install coveralls
    - pip install wget
    - pip install nibabel
    - pip install nilearn
    - pip install scipy
    - pip install dipy
    - pip install sklearn
    - pip install networkx
    - pip install .
script:
    - coverage run -m unittest discover
after_success: coveralls
